### ISSUE TITLE
Set a godot object to null

### ISSUE THREAD

**Issue by Ev1lbl0w** [GodotNativeTools/godot-d#50]
Is there an equivalent to setting an object to null? I can compare for null in boolean operations, but for some reason I can't set it to null. *(in my case it's a KinematicBody object)* Using `memdelete` is no option to me, since i'm not supposed to delete the object.

**Comment by Ev1lbl0w** [comment]
I found a way to work, and it is setting the objects to `init`:
*(`KinematicBody kBody = KinematicBody.init;`)*
Is this the right way?

**Comment by sheepandshepherd** [comment]
Yes, `SomeGodotClass.init` is equivalent to `null`. It's one of the ugly things in this plugin, unfortunately.

I can't represent Godot's original classes as real D `class`es because their "class-like" behaviors (inheritance, casting, virtual functions, etc.) are all different from D. So they're fake struct wrappers that act like classes. So far it seems impossible to make `null` work with them, so I'll close this issue for now, but feel free to reopen if anyone finds a solution.
